import { describe, expect, it } from 'vitest';
import { mulberry32 } from './rng';
import {
	createJudge,
	createPolicy,
	expectedScore,
	fitJudge,
	geneFromU,
	klToRef,
	N_GENES,
	preferProb,
	REF_SIGMA,
	sampleRefGene,
	sampleRefU,
	samplePolicyGene,
	score,
	scoreGrad,
	uFromGene,
	ascendStep,
	type Gene,
	type Pair
} from './preference';

const refSample = (n: number, seed = 7): Gene[] => {
	const rand = mulberry32(seed);
	return Array.from({ length: n }, () => sampleRefGene(rand));
};

describe('the gene space', () => {
	it('round-trips through the logistic squash', () => {
		const rand = mulberry32(11);
		const u = sampleRefU(rand);
		const back = uFromGene(geneFromU(u));
		for (let i = 0; i < N_GENES; i++) expect(back[i]).toBeCloseTo(u[i], 8);
	});

	it('keeps every gene inside [0,1]', () => {
		const rand = mulberry32(3);
		for (let k = 0; k < 200; k++) {
			const g = sampleRefGene(rand);
			for (let i = 0; i < N_GENES; i++) {
				expect(g[i]).toBeGreaterThan(0);
				expect(g[i]).toBeLessThan(1);
			}
		}
	});
});

describe('the judge', () => {
	it('agrees with finite differences of its own score', () => {
		const j = createJudge(mulberry32(5));
		// a fitted judge has structure; an unfitted one is nearly flat, so fit
		// first or the check is vacuous
		fitJudge(j, syntheticPairs(40, 21), { steps: 200, refSample: refSample(200) });

		const g = sampleRefGene(mulberry32(99));
		const analytic = scoreGrad(j, g);
		const h = 1e-5;
		for (let i = 0; i < N_GENES; i++) {
			const up = Float64Array.from(g);
			const dn = Float64Array.from(g);
			up[i] += h;
			dn[i] -= h;
			const numeric = (score(j, up) - score(j, dn)) / (2 * h);
			expect(analytic[i]).toBeCloseTo(numeric, 4);
		}
	});

	it('learns a taste it can be shown, and predicts unseen comparisons', () => {
		const j = createJudge(mulberry32(5));
		const train = syntheticPairs(48, 21);
		const { fit, loss } = fitJudge(j, train, { refSample: refSample(200) });
		expect(fit).toBeGreaterThan(0.9);
		expect(loss).toBeLessThan(Math.LN2);

		// held out: pairs it has never seen, generated by the same taste
		const test = syntheticPairs(120, 4242);
		let right = 0;
		for (const p of test) if (preferProb(j, p.winner, p.loser) > 0.5) right++;
		expect(right / test.length).toBeGreaterThan(0.75);
	});

	it('standardizes its scores against the reference pile', () => {
		const j = createJudge(mulberry32(5));
		const sample = refSample(400);
		fitJudge(j, syntheticPairs(40, 21), { refSample: sample });
		let m = 0;
		for (const g of sample) m += score(j, g);
		m /= sample.length;
		let v = 0;
		for (const g of sample) v += (score(j, g) - m) ** 2;
		expect(m).toBeCloseTo(0, 6);
		expect(Math.sqrt(v / sample.length)).toBeCloseTo(1, 6);
	});

	it('is symmetric: preferring a over b is not preferring b over a', () => {
		const j = createJudge(mulberry32(5));
		fitJudge(j, syntheticPairs(40, 21), { refSample: refSample(200) });
		const rand = mulberry32(88);
		for (let k = 0; k < 50; k++) {
			const a = sampleRefGene(rand);
			const b = sampleRefGene(rand);
			expect(preferProb(j, a, b) + preferProb(j, b, a)).toBeCloseTo(1, 10);
		}
	});
});

describe('the leash', () => {
	it('is zero exactly at the reference and positive everywhere else', () => {
		const p = createPolicy();
		expect(klToRef(p)).toBeCloseTo(0, 12);
		p.mu[0] = 0.4;
		expect(klToRef(p)).toBeGreaterThan(0);
		const q = createPolicy();
		q.logSigma[2] = Math.log(REF_SIGMA * 0.5);
		expect(klToRef(q)).toBeGreaterThan(0);
	});

	it('matches a Monte Carlo estimate of the same divergence', () => {
		const p = createPolicy();
		p.mu[0] = 0.9;
		p.mu[3] = -0.5;
		p.logSigma[1] = Math.log(0.7);
		const rand = mulberry32(1234);
		const n = 200_000;
		let acc = 0;
		for (let k = 0; k < n; k++) {
			let lp = 0;
			let lq = 0;
			for (let i = 0; i < N_GENES; i++) {
				const s = Math.exp(p.logSigma[i]);
				const u = p.mu[i] + s * gaussFrom(rand);
				lp += -Math.log(s) - (u - p.mu[i]) ** 2 / (2 * s * s);
				lq += -Math.log(REF_SIGMA) - (u * u) / (2 * REF_SIGMA * REF_SIGMA);
			}
			acc += lp - lq;
		}
		expect(acc / n).toBeCloseTo(klToRef(p), 1);
	});
});

describe('optimizing against the judge', () => {
	it('unleashed, it climbs the proxy and travels far from the reference', () => {
		const j = createJudge(mulberry32(5));
		fitJudge(j, syntheticPairs(40, 21), { refSample: refSample(200) });
		const p = createPolicy();
		const rand = mulberry32(2);
		const before = expectedScore(j, p, mulberry32(50), 400);
		for (let k = 0; k < 400; k++) ascendStep(j, p, rand, { beta: 0 });
		const after = expectedScore(j, p, mulberry32(50), 400);
		expect(after).toBeGreaterThan(before + 0.5);
		expect(klToRef(p)).toBeGreaterThan(2);
	});

	it('leashed, it still improves but stays recognizable', () => {
		const j = createJudge(mulberry32(5));
		fitJudge(j, syntheticPairs(40, 21), { refSample: refSample(200) });
		const rand = mulberry32(2);

		const loose = createPolicy();
		for (let k = 0; k < 400; k++) ascendStep(j, loose, rand, { beta: 0 });
		const tight = createPolicy();
		for (let k = 0; k < 400; k++) ascendStep(j, tight, rand, { beta: 1.5 });

		expect(klToRef(tight)).toBeLessThan(klToRef(loose));
		const base = expectedScore(j, createPolicy(), mulberry32(50), 400);
		expect(expectedScore(j, tight, mulberry32(50), 400)).toBeGreaterThan(base);
	});

	it('a leash pulled tight enough never leaves the reference', () => {
		const j = createJudge(mulberry32(5));
		fitJudge(j, syntheticPairs(40, 21), { refSample: refSample(200) });
		const p = createPolicy();
		const rand = mulberry32(2);
		for (let k = 0; k < 400; k++) ascendStep(j, p, rand, { beta: 60 });
		expect(klToRef(p)).toBeLessThan(0.05);
	});

	it('keeps every sample drawable however hard it is pushed', () => {
		const j = createJudge(mulberry32(5));
		fitJudge(j, syntheticPairs(40, 21), { refSample: refSample(200) });
		const p = createPolicy();
		const rand = mulberry32(2);
		for (let k = 0; k < 1500; k++) ascendStep(j, p, rand, { beta: 0 });
		const draw = mulberry32(17);
		for (let k = 0; k < 200; k++) {
			const g = samplePolicyGene(p, draw);
			for (let i = 0; i < N_GENES; i++) {
				expect(Number.isFinite(g[i])).toBe(true);
				expect(g[i]).toBeGreaterThanOrEqual(0);
				expect(g[i]).toBeLessThanOrEqual(1);
			}
		}
	});
});

// ── a stand-in reader, so the tests never depend on anyone's actual taste ──
//
// A fixed "true" preference with an interior optimum: middling arms, a little
// curl, generous reach, light stroke. The judge has to discover it from
// nothing but which-of-two, exactly as it does from a real reader.
const TRUE_BEST = [0.45, 0.62, 0.78, 0.25, 0.35, 0.55];

function trueScore(g: Gene): number {
	let s = 0;
	for (let i = 0; i < N_GENES; i++) {
		const d = g[i] - TRUE_BEST[i];
		s -= d * d;
	}
	return s * 3;
}

function syntheticPairs(n: number, seed: number): Pair[] {
	const rand = mulberry32(seed);
	const out: Pair[] = [];
	for (let k = 0; k < n; k++) {
		const a = sampleRefGene(rand);
		const b = sampleRefGene(rand);
		out.push(trueScore(a) >= trueScore(b) ? { winner: a, loser: b } : { winner: b, loser: a });
	}
	return out;
}

function gaussFrom(rand: () => number): number {
	let a = rand();
	if (a < 1e-12) a = 1e-12;
	return Math.sqrt(-2 * Math.log(a)) * Math.cos(2 * Math.PI * rand());
}
